# backend/accounts/migrations/0002_rbac_safe_matric_unique.py
#
# HOW TO USE
# ──────────────────────────────────────────────────────────────────────────────
# 1. Delete the broken migration that was auto-generated:
#       backend/accounts/migrations/0002_alter_user_options_user_role_...py
#    (whatever Django named it — delete only that file, not 0001_initial.py)
#
# 2. Place THIS file in its place as:
#       backend/accounts/migrations/0002_rbac_safe_matric_unique.py
#
# 3. Run:  python manage.py migrate
# ──────────────────────────────────────────────────────────────────────────────
#
# What this migration does (in order):
#   Step A — DATA: Null-out any matric number that looks like an auto-generated
#            TEMP placeholder ("TEMP-*"), or that is blank/whitespace.
#   Step B — DATA: Detect any remaining duplicates and null them out,
#            keeping only the FIRST registered user's value (oldest id).
#   Step C — SCHEMA: Add the `role` field.
#   Step D — SCHEMA: Alter `matric_number` → unique=True, null=True, blank=True,
#            with the updated validator for normalized (uppercase) format.
#   Step E — SCHEMA: Tighten db_index and verbose_name on email.

from django.db import migrations, models
import django.core.validators


# ─── Data-migration helpers ────────────────────────────────────────────────────

def clean_temp_matric_numbers(apps, schema_editor):
    """
    Step A: Null-out TEMP placeholders and blank/whitespace matric numbers.
    These were generated by the old User.save() auto-generator and are
    meaningless — treating them as NULL is safe and correct.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(matric_number__startswith="TEMP-").update(matric_number=None)
    User.objects.filter(matric_number="").update(matric_number=None)


def resolve_duplicate_matric_numbers(apps, schema_editor):
    """
    Step B: Null-out duplicate matric numbers, keeping only the earliest
    registered user (lowest pk) for each duplicated value.

    This is safe because:
    - Duplicates only existed due to the old TEMP generator assigning the
      same random string to different users (extremely rare but possible).
    - Real student matric numbers entered by hand are unique by definition.
    - Any nulled-out user can re-enter their matric via the profile API.
    """
    User = apps.get_model("accounts", "User")

    # Collect all non-null matric numbers that appear more than once
    seen = {}        # matric_number → first (lowest pk) user id
    duplicates = []  # pks to null-out

    # Order by pk ascending so the first registered user is kept
    for user in User.objects.exclude(matric_number__isnull=True).order_by("id"):
        matric = user.matric_number
        if matric in seen:
            duplicates.append(user.pk)
        else:
            seen[matric] = user.pk

    if duplicates:
        User.objects.filter(pk__in=duplicates).update(matric_number=None)


def normalize_existing_matric_numbers(apps, schema_editor):
    """
    Step C (data): Uppercase + strip any surviving real matric numbers so they
    conform to the normalized format before the unique index is built.
    """
    User = apps.get_model("accounts", "User")
    for user in User.objects.exclude(matric_number__isnull=True):
        normalized = user.matric_number.strip().upper()
        if normalized != user.matric_number:
            user.matric_number = normalized
            user.save()


# ─── Migration ─────────────────────────────────────────────────────────────────

class Migration(migrations.Migration):

    dependencies = [
        # Must come after the initial accounts migration
        ("accounts", "0001_initial"),
    ]

    operations = [
        # ── Step A: Null-out TEMP placeholders ────────────────────────────
        migrations.RunPython(
            clean_temp_matric_numbers,
            reverse_code=migrations.RunPython.noop,
        ),

        # ── Step B: Resolve any remaining duplicates ───────────────────────
        migrations.RunPython(
            resolve_duplicate_matric_numbers,
            reverse_code=migrations.RunPython.noop,
        ),

        # ── Step C (data): Normalize surviving matric numbers ──────────────
        migrations.RunPython(
            normalize_existing_matric_numbers,
            reverse_code=migrations.RunPython.noop,
        ),

        # ── Step D (schema): Add role field ───────────────────────────────
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                db_index=True,
                default="user",
                max_length=10,
            ),
        ),

        # ── Step E (schema): Alter matric_number → unique, updated validator
        # Now safe because duplicates and TEMP values have been nulled out.
        migrations.AlterField(
            model_name="user",
            name="matric_number",
            field=models.CharField(
                blank=True,
                help_text="Normalized format: '23/SCI01/002' or '202330217286FA'.",
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex=r'^(\d{2}/[A-Z]{3}\d{2}/\d{3}|\d{12}[A-Z]{2})$',
                        message=(
                            "Matric number must be in format '23/SCI01/002' "
                            "or JAMB Reg Number e.g. '202330217286FA'."
                        ),
                    )
                ],
            ),
        ),

        # ── Step F (schema): Update email field (index + verbose options) ──
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),

        # ── Step G (schema): Update Meta options ──────────────────────────
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]