# Generated by Django 5.2.4 on 2026-04-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_notification_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_login_enabled',
            field=models.BooleanField(default=False, help_text='Set to True when the user has enrolled face embeddings.'),
        ),
    ]
