# Generated by Django 5.2.4 on 2026-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_drop_face_auth_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='student', help_text='Chosen at signup. Staff accounts require admin approval (see is_approved).', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Staff signups start False and can log in but see a pending-approval view until an Admin/Super Admin assigns them a role. Students are always True.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('technician', 'Technician'), ('lecturer', 'Lecturer'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('president', 'President'), ('vice_president', 'Vice President'), ('general_secretary', 'General Secretary'), ('asst_general_secretary', 'Assistant General Secretary'), ('financial_secretary', 'Financial Secretary'), ('software_director', 'Software Director'), ('hardware_director', 'Hardware Director'), ('social_director', 'Social Director'), ('welfare_director', 'Welfare Director'), ('academic_director', 'Academic Director'), ('public_relations_officer', 'Public Relations Officer'), ('sports_director', 'Sports Director'), ('chief_of_staff', 'Chief of Staff')], db_index=True, default='user', max_length=30),
        ),
    ]
