# Generated by Django 5.2.4 on 2026-09-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_account_type_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matric_edit_allowed',
            field=models.BooleanField(default=False, help_text='Super Admin toggle: while True the user may set/change their own matric number from their profile. Stays on until switched off.'),
        ),
        migrations.CreateModel(
            name='MatricEditLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
