# Generated by Django 5.2.4 on 2026-10-09 16:15

from django.db import migrations, models


# The executive titles that used to be hard-coded on User.Role, followed by
# the three added for 26/27. Values are unchanged so existing users keep them.
INITIAL_EXECUTIVE_ROLES = [
    ("president", "President"),
    ("vice_president", "Vice President"),
    ("general_secretary", "General Secretary"),
    ("asst_general_secretary", "Assistant General Secretary"),
    ("financial_secretary", "Financial Secretary"),
    ("software_director", "Software Director"),
    ("hardware_director", "Hardware Director"),
    ("social_director", "Social Director"),
    ("welfare_director", "Welfare Director"),
    ("academic_director", "Academic Director"),
    ("public_relations_officer", "Public Relations Officer"),
    ("sports_director", "Sports Director"),
    ("chief_of_staff", "Chief of Staff"),
    ("director_of_skills_hub", "Director of Skills Hub"),
    ("editor_in_chief", "Editor-in-Chief"),
    ("director_of_mentorship", "Director of Mentorship"),
]


def seed_executive_roles(apps, schema_editor):
    ExecutiveRole = apps.get_model("accounts", "ExecutiveRole")
    for order, (value, label) in enumerate(INITIAL_EXECUTIVE_ROLES):
        ExecutiveRole.objects.get_or_create(
            value=value, defaults={"label": label, "display_order": order}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_matric_editing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='user', max_length=30),
        ),
        migrations.RunPython(seed_executive_roles, migrations.RunPython.noop),
    ]
