# Generated by Django 5.2.4 on 2026-10-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_email_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpayment',
            name='needs_attention',
            field=models.CharField(blank=True, choices=[('', 'Nothing to do'), ('duplicate_payment', 'Paid twice: refund one'), ('underpaid', 'Paid less than the price (or wrong currency): refund'), ('ticket_missing', 'Paid but the ticket was deleted: refund'), ('partial_refund', 'Partly refunded: decide whether the ticket stays valid'), ('disputed', 'Disputed by the bank: respond in Paystack')], db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
