# Generated by Django 5.2.4 on 2026-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_scrub_gateway_payloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='sales_closed',
            field=models.BooleanField(default=False),
        ),
    ]
