# Generated by Django 5.2.4 on 2026-10-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_ticket_type_sales_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
