# Generated by Django 5.2.4 on 2026-05-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_fix_collaboration_constraints'),
        ('projects', '0004_collaborationneed_collaborationrequest'),
    ]

    operations = [
    ]
