# Generated by Django 5.2.4 on 2026-07-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20260502_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
